services:
  backend:
    image: poojadevarmanii/backend:staging
    ports:
      - "5000:5000"
    environment:
      - ENV=staging
    depends_on:
      - db

  frontend:
    image: poojadevarmanii/frontend:staging
    ports:
      - "8081:80"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
