name: CI-CD Pipeline (Staging)

on:
  push:
    branches:
      main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
        name: Checkout code
        uses: actions/checkout@v4

        name: Set up Docker
        uses: docker/setup-buildx-action@v3

        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        name: Build backend image
        run: docker build -t poojadevarmanii/backend:staging ./backend

        name: Run backend tests
        run: docker run poojadevarmanii/backend:staging pytest

        name: Trivy scan backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: poojadevarmanii/backend:staging
          severity: CRITICAL
          exit-code: 0

        name: Push backend image
        run: docker push poojadevarmanii/backend:staging

        name: Build & push frontend image
        run: |
          docker build -t poojadevarmanii/frontend:staging ./frontend
          docker push poojadevarmanii/frontend:staging
